Feat/base layout
uranussolutions/minhdu-fontend pull request #24
Opened 2021-04-19 16:11 UTC by vansuphan

2021-04-20 07:38 UTC, uranussolutions approved these changes

2021-04-20 07:38 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +  handleClickMenu?: Function,
` handleClickMenu?: (value: string) => void`

2021-04-20 07:38 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +          <a onClick={_handleRouter}>
tag `<a>` yêu cầu 1 href 
![Screen Shot 2021-04-20 at 14 29 49](https://user-images.githubusercontent.com/48413548/115355509-f0d46980-a1e4-11eb-9710-d3355b1afd48.png)

2021-04-20 07:38 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +            onClick={_onClick}
Component Menu k có thuộc tính onClick 
![Screen Shot 2021-04-20 at 14 30 54](https://user-images.githubusercontent.com/48413548/115355655-1497af80-a1e5-11eb-945d-76c75ab728d5.png)

2021-04-20 07:38 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +                    return <SubMenu theme="dark"
Component Submenu không có theme
![Screen Shot 2021-04-20 at 14 32 56](https://user-images.githubusercontent.com/48413548/115355931-5a547800-a1e5-11eb-8792-37f2c7b63ea9.png)

2021-04-20 07:38 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +                : <></>
Những cặp thẻ như này thì nên để `<div />` cho gọn code
![Screen Shot 2021-04-20 at 14 34 07](https://user-images.githubusercontent.com/48413548/115356147-8ff96100-a1e5-11eb-83bf-73b8c2a1e636.png)

2021-04-20 07:38 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +export default ComponentsBaseLayout;
export trên func luôn cho gọn code

2021-04-20 07:39 UTC, uranussolutions commented
Mỗi file chỉ làm 1 nhiệm vụ. nên chia interface riêng nằm ngoài compontent
![Screen Shot 2021-04-20 at 14 39 08](https://user-images.githubusercontent.com/48413548/115356750-2af23b00-a1e6-11eb-84ca-47f3e26e9076.png)
Trong interface chia nhỏ model ra
![Screen Shot 2021-04-20 at 14 39 22](https://user-images.githubusercontent.com/48413548/115356799-35143980-a1e6-11eb-8ddc-8dee4e17f397.png)
![Screen Shot 2021-04-20 at 14 39 32](https://user-images.githubusercontent.com/48413548/115356820-3a718400-a1e6-11eb-89b8-8af2f003039e.png)


Chia nhỏ nhiệm vụ chức năng

2021-04-20 07:44 UTC, uranussolutions commented on apps/human-resource/pages/index.tsx
> +  return (<div>
format div xuống cho đồng bộ với dấu ngoặc đóng. khong ai viết kiểu này cả
`if(condition) { a= 5
    b = 7
}`

2021-04-20 07:50 UTC, uranussolutions requested changes

2021-04-20 07:50 UTC, uranussolutions commented on apps/human-resource/pages/index.tsx
> +  const handleClickMenu = (value) => {
kiểu dữ liệu value

2021-04-20 07:50 UTC, uranussolutions commented on apps/human-resource/pages/index.tsx
> +      logo={"./nx-logo-white.svg"}
khi nào là tham số mới cần dùng { } => `logo="./nx-logo-white.svg"`
Tương tự tất cả các mục

2021-04-20 07:50 UTC, uranussolutions commented on apps/human-resource/pages/index.tsx
>  export function Index() {
check lại export. Tất cả đều export trên func cho dễ quản lý
![Screen Shot 2021-04-20 at 14 47 37](https://user-images.githubusercontent.com/48413548/115357943-5b86a480-a1e7-11eb-968d-0e778985d6bd.png)

2021-04-20 07:50 UTC, uranussolutions commented on libs/components/base-layout/src/lib/components-base-layout.spec.tsx
> +import { render } from '@testing-library/react';
Xoá các file spec của component đi. Chỗ nào có logic thì mới để

2021-04-20 16:46 UTC, vansuphan commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +                : <></>
hai thẻ có chức năng khác nhau, một thẻ là không có gì một thẻ là tạo ra 1 div element

2021-04-20 17:04 UTC, vansuphan commented on libs/components/base-layout/src/lib/components-base-layout.tsx
> +            onClick={_onClick}
chỗ này m dựa vào bắt lỗi kiểu đó thì t chịu
<img width="1013" alt="Screen Shot 2021-04-21 at 00 03 22" src="https://user-images.githubusercontent.com/37709216/115436327-0e312400-a235-11eb-95a2-1921ef25ac2a.png">

2021-04-21 09:43 UTC, uranussolutions approved these changes

2021-04-21 09:43 UTC, merged